import { query } from './store.js';
export function boundaries(now = new Date(), offset = 330) { const local = new Date(+now + offset * 60000); const day = local.toISOString().slice(0, 10); const midnight = Date.parse(day + 'T00:00:00Z'); const week = midnight - ((local.getUTCDay() + 6) % 7) * 86400000; return { day, midnight, week, month: Date.parse(day.slice(0, 7) + '-01T00:00:00Z'), offset }; }
export async function dashboard(playerId) {
    const [player] = await query('SELECT * FROM PLAYERS WHERE player_id=?', [playerId]);
    if (!player) return null;
    const b = boundaries(new Date(), player.timezone_offset_minutes);
    const daily = await query(`WITH RECURSIVE days AS (SELECT DATE(DATE_ADD(UTC_TIMESTAMP(), INTERVAL ? MINUTE)) - INTERVAL 61 DAY AS day UNION ALL SELECT day + INTERVAL 1 DAY FROM days WHERE day < DATE(DATE_ADD(UTC_TIMESTAMP(), INTERVAL ? MINUTE))) SELECT DATE_FORMAT(d.day,'%Y-%m-%d') AS day, ROUND(COALESCE(SUM(GREATEST(0,TIMESTAMPDIFF(SECOND,GREATEST(s.session_start,DATE_SUB(d.day,INTERVAL ? MINUTE)),LEAST(COALESCE(s.session_end,UTC_TIMESTAMP()),DATE_SUB(d.day + INTERVAL 1 DAY,INTERVAL ? MINUTE))))),0)/60,2) AS minutes FROM days d LEFT JOIN PLAYER_SESSIONS s ON s.player_id=? AND s.session_start<DATE_SUB(d.day + INTERVAL 1 DAY,INTERVAL ? MINUTE) AND COALESCE(s.session_end,UTC_TIMESTAMP())>DATE_SUB(d.day,INTERVAL ? MINUTE) GROUP BY d.day ORDER BY d.day`, [b.offset, b.offset, b.offset, b.offset, playerId, b.offset, b.offset]);
    const [games, purchases, sessions, limits, achievements, history] = await Promise.all([
        query(`SELECT g.*,COUNT(s.session_id) AS sessions,ROUND(COALESCE(SUM(TIMESTAMPDIFF(SECOND,s.session_start,COALESCE(s.session_end,UTC_TIMESTAMP()))),0)/60,2) AS minutes FROM GAMES g JOIN (SELECT DISTINCT game_id FROM PLAYER_GAME_LIBRARY WHERE player_id=?) l ON l.game_id=g.game_id LEFT JOIN PLAYER_SESSIONS s ON s.game_id=g.game_id AND s.player_id=? GROUP BY g.game_id ORDER BY minutes DESC`, [playerId, playerId]),
        query('SELECT p.*,g.game_name FROM PURCHASES p JOIN GAMES g USING(game_id) WHERE player_id=? ORDER BY purchase_date DESC', [playerId]),
        query(`SELECT s.*,g.game_name,g.color,p.platform_name,ROUND(TIMESTAMPDIFF(SECOND,s.session_start,COALESCE(s.session_end,UTC_TIMESTAMP()))/60,2) AS elapsed_minutes,CASE WHEN HOUR(DATE_ADD(session_start,INTERVAL ? MINUTE))<6 THEN 'After midnight' WHEN HOUR(DATE_ADD(session_start,INTERVAL ? MINUTE))>=22 THEN 'Late night' WHEN HOUR(DATE_ADD(session_start,INTERVAL ? MINUTE))>=18 THEN 'Evening' ELSE 'Daytime' END AS time_category FROM PLAYER_SESSIONS s JOIN GAMES g USING(game_id) JOIN PLATFORMS p USING(platform_id) WHERE player_id=? ORDER BY session_start DESC`, [b.offset, b.offset, b.offset, playerId]),
        query('SELECT * FROM PLAYER_LIMITS WHERE player_id=?', [playerId]),
        query('SELECT a.*,g.game_name,pa.earned_at FROM ACHIEVEMENTS a JOIN GAMES g USING(game_id) JOIN (SELECT DISTINCT game_id FROM PLAYER_GAME_LIBRARY WHERE player_id=?) l ON l.game_id=a.game_id LEFT JOIN PLAYER_ACHIEVEMENTS pa ON pa.achievement_id=a.achievement_id AND pa.player_id=? ORDER BY pa.earned_at DESC,a.achievement_id', [playerId, playerId]),
        query('SELECT * FROM LIMIT_HISTORY WHERE player_id=? ORDER BY effective_from DESC,history_id DESC', [playerId])]);
    const sum = (from, to = Infinity) => daily.filter(d => Date.parse(d.day + 'T00:00:00Z') >= from && Date.parse(d.day + 'T00:00:00Z') < to).reduce((s, d) => s + Number(d.minutes), 0);
    const week = sum(b.week), lastWeek = sum(b.week - 7 * 86400000, b.week), last30 = daily.slice(-30), avg = last30.reduce((s, d) => s + Number(d.minutes), 0) / 30;

    // Purchase month uses the player's local date, just like session buckets.
    const localMonth = p => new Date(Date.parse(p.purchase_date.replace(' ', 'T') + 'Z') + b.offset * 60000).toISOString().slice(0, 7);
    const monthlySpend = purchases.filter(p => localMonth(p) === b.day.slice(0, 7)).reduce((s, p) => s + p.amount, 0);
    const previousMonth = new Date(b.month - 86400000).toISOString().slice(0, 7);
    const previousSpend = purchases.filter(p => localMonth(p) === previousMonth).reduce((s, p) => s + p.amount, 0);
    const spendGames = games.map(g => ({ ...g, spent: purchases.filter(p => p.game_id === g.game_id).reduce((s, p) => s + p.amount, 0) })).sort((a, b) => b.spent - a.spent);
    const busiest = last30.reduce((a, d) => d.minutes > a.minutes ? d : a, { day: null, minutes: 0 });
    return { player, daily: daily.slice(-30), games, purchases, sessions, limits: limits[0] || null, achievements, history, summary: { today: sum(b.midnight), week, month: sum(b.month), last_week: lastWeek, week_change: lastWeek ? Math.round((week - lastWeek) / lastWeek * 100) : null, average_daily: avg, active_days: last30.filter(d => d.minutes > 0).length, longest_session: Math.max(0, ...sessions.map(s => s.elapsed_minutes)), total_spending: purchases.reduce((s, p) => s + p.amount, 0), monthly_spending: monthlySpend, previous_month_spending: previousSpend, spending_change: previousSpend ? Math.round((monthlySpend - previousSpend) / previousSpend * 100) : null, purchase_count: purchases.length, most_spent_game: spendGames[0]?.spent ? spendGames[0] : null, most_played: games[0]?.minutes ? games[0] : null, most_sessions: [...games].sort((a, b) => b.sessions - a.sessions)[0] || null, busiest_day: busiest, engagement: avg < 60 ? 'Low' : avg < 120 ? 'Moderate' : avg < 240 ? 'High' : 'Very high', late_night_sessions: sessions.filter(s => ['After midnight', 'Late night'].includes(s.time_category)).length, achievement_points: achievements.filter(a => a.earned_at).reduce((s, a) => s + a.points, 0) } };
}
