import express from 'express';
import cors from 'cors';
import { fileURLToPath } from 'node:url';
import { query, transaction, config } from './store.js';
import { dashboard } from './analytics.js';
export const app = express();

app.disable('x-powered-by'); app.use(cors({ origin: ['http://localhost:5000', 'http://127.0.0.1:5000'] })); app.use(express.json({ limit: '16kb' }));

const fail = (message, status = 400) => Object.assign(new Error(message), { status });

const id = v => { if (!Number.isSafeInteger(Number(v)) || Number(v) < 1) throw fail('A valid positive ID is required.'); return Number(v); };

const positive = (v, max) => { if (typeof v !== 'number' || !Number.isFinite(v) || v <= 0 || v > max) throw fail('Enter a positive value within the allowed range.'); return v; };
app.get('/', (req, res) => res.type('text').send('Gaming Habit & Behavior Analyzer API is running!'));
app.get('/health', async (req, res) => { const [actual] = await query('SELECT DATABASE() AS name, @@port AS port'); res.json({ status: 'ok', database: 'mysql', connection: { host: config.host, port: actual.port, name: actual.name } }); });
app.get('/players', async (req, res) => res.json(await query('SELECT * FROM PLAYERS ORDER BY username')));
app.get('/games', async (req, res) => res.json(await query('SELECT * FROM GAMES ORDER BY game_name')));
app.get('/library/:playerId', async (req, res) => res.json(await query('SELECT l.*,g.game_name,p.platform_name FROM PLAYER_GAME_LIBRARY l JOIN GAMES g USING(game_id) JOIN PLATFORMS p USING(platform_id) WHERE player_id=? ORDER BY game_name', [id(req.params.playerId)])));
app.get('/dashboard/:playerId', async (req, res) => { const data = await dashboard(id(req.params.playerId)); if (!data) throw fail('Player not found.', 404); res.json(data); });
app.get('/analysis/:metric/:playerId', async (req, res) => { const d = await dashboard(id(req.params.playerId)); if (!d) throw fail('Player not found.', 404); const map = { today: { minutes: d.summary.today }, week: { minutes: d.summary.week }, month: { minutes: d.summary.month }, spending: { total: d.summary.total_spending, monthly: d.summary.monthly_spending }, 'most-played': d.summary.most_played, 'longest-session': { minutes: d.summary.longest_session } }; if (!(req.params.metric in map)) throw fail('Analysis not found.', 404); res.json(map[req.params.metric]); });
app.get('/sessions/:playerId', async (req, res) => res.json(await query('SELECT s.*,g.game_name FROM PLAYER_SESSIONS s JOIN GAMES g USING(game_id) WHERE player_id=? ORDER BY session_start DESC', [id(req.params.playerId)])));
app.post('/sessions/start', async (req, res) => { const player = id(req.body.player_id), game = id(req.body.game_id); const library = await query('SELECT platform_id FROM PLAYER_GAME_LIBRARY WHERE player_id=? AND game_id=? ORDER BY platform_id', [player, game]); if (!library.length) throw fail('Choose a game from this player’s library.'); const platform = req.body.platform_id ? id(req.body.platform_id) : library[0].platform_id; if (!library.some(p => p.platform_id === platform)) throw fail('This platform is not in the player’s library.'); const r = await query('INSERT INTO PLAYER_SESSIONS(player_id,game_id,platform_id,session_start) VALUES(?,?,?,UTC_TIMESTAMP())', [player, game, platform]); res.status(201).json({ session_id: r.insertId }); });
app.post('/sessions/end', async (req, res) => { const r = await query('UPDATE PLAYER_SESSIONS SET session_end=UTC_TIMESTAMP() WHERE player_id=? AND session_end IS NULL', [id(req.body.player_id)]); if (!r.affectedRows) throw fail('No active session to end.', 409); res.json({ message: 'Session saved.' }); });
app.post('/purchases', async (req, res) => { const player = id(req.body.player_id), game = id(req.body.game_id), amount = positive(req.body.amount, 10000000); if (!['Game', 'In-game'].includes(req.body.purchase_type)) throw fail('Choose a valid purchase type.'); if (typeof req.body.note !== 'string' || req.body.note.length > 200) throw fail('Note must be at most 200 characters.'); if (!Number.isInteger(Math.round(amount * 100) * 1) || Math.abs(amount * 100 - Math.round(amount * 100)) > 0.00001) throw fail('Use at most two decimal places.'); const l = await query('SELECT 1 FROM PLAYER_GAME_LIBRARY WHERE player_id=? AND game_id=? LIMIT 1', [player, game]); if (!l.length) throw fail('Choose a game from this player’s library.'); const r = await query('INSERT INTO PURCHASES(player_id,game_id,amount,purchase_type,note) VALUES(?,?,?,?,?)', [player, game, amount, req.body.purchase_type, req.body.note.trim()]); res.status(201).json({ purchase_id: r.insertId }); });
app.put('/limits/:playerId', async (req, res) => { const player = id(req.params.playerId), daily = positive(req.body.daily_playtime_limit, 1440), weekly = positive(req.body.weekly_playtime_limit, 10080), monthly = positive(req.body.monthly_spending_limit, 10000000); if (!Number.isInteger(daily) || !Number.isInteger(weekly)) throw fail('Playtime limits must be whole minutes.'); const reason = req.body.change_reason; if (typeof reason !== 'string' || !reason.trim() || reason.length > 200) throw fail('Enter a change reason of 1–200 characters.'); await transaction(async q => { const p = await q('SELECT player_id FROM PLAYERS WHERE player_id=? FOR UPDATE', [player]); if (!p.length) throw fail('Player not found.', 404); await q('INSERT INTO PLAYER_LIMITS VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE daily_playtime_limit=?,weekly_playtime_limit=?,monthly_spending_limit=?', [player, daily, weekly, monthly, daily, weekly, monthly]); await q('UPDATE LIMIT_HISTORY SET effective_to=UTC_TIMESTAMP(3) WHERE player_id=? AND effective_to IS NULL', [player]); await q('INSERT INTO LIMIT_HISTORY(player_id,daily_playtime_limit,weekly_playtime_limit,monthly_spending_limit,change_reason) VALUES(?,?,?,?,?)', [player, daily, weekly, monthly, reason.trim()]); }); res.json({ message: 'Limits updated.' }); });
app.post('/achievements/earn', async (req, res) => { const player = id(req.body.player_id), achievement = id(req.body.achievement_id); const rows = await query('SELECT 1 FROM ACHIEVEMENTS a JOIN PLAYER_GAME_LIBRARY l USING(game_id) WHERE l.player_id=? AND a.achievement_id=? LIMIT 1', [player, achievement]); if (!rows.length) throw fail('Achievement is not in this player’s library.'); await query('INSERT INTO PLAYER_ACHIEVEMENTS(player_id,achievement_id) VALUES(?,?)', [player, achievement]); res.status(201).json({ message: 'Achievement recorded.' }); });
app.use('/dashboard', express.static(fileURLToPath(new URL('../frontend', import.meta.url))));
app.use((req, res) => res.status(404).json({ error: 'Route not found.' }));
app.use((err, req, res, next) => { if (err.code === 'ER_DUP_ENTRY') return res.status(409).json({ error: 'An active session or achievement already exists.' }); if (err.type === 'entity.parse.failed') return res.status(400).json({ error: 'Invalid JSON.' }); if (!err.status) console.error(err.code || err.message); res.status(err.status || 500).json({ error: err.status ? err.message : 'Database request failed. Check server configuration.' }); });
if (process.argv[1] === fileURLToPath(import.meta.url)) { const port = Number(process.env.PORT || 5000); app.listen(port, process.env.HOST || '127.0.0.1', () => console.log(`Dashboard: http://127.0.0.1:${port}/dashboard/`)); }
