import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {app} from '../backend/app.js';
import {query,pool} from '../backend/store.js';
import {boundaries} from '../backend/analytics.js';
let server,base,player;
async function request(path,method='GET',body){const res=await fetch(base+path,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return {status:res.status,data:await res.json()};}
before(async()=>{server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base=`http://127.0.0.1:${server.address().port}`;const p=await query('INSERT INTO PLAYERS(username,timezone_offset_minutes) VALUES(?,0)',['test-'+Date.now()]);player=p.insertId;await query('INSERT INTO PLAYER_GAME_LIBRARY(player_id,game_id,platform_id) VALUES(?,1,1)',[player]);});
after(async()=>{if(player){for(const t of ['PLAYER_ACHIEVEMENTS','PLAYER_SESSIONS','PURCHASES','LIMIT_HISTORY','PLAYER_LIMITS','PLAYER_GAME_LIBRARY'])await query(`DELETE FROM ${t} WHERE player_id=?`,[player]);await query('DELETE FROM PLAYERS WHERE player_id=?',[player]);}await new Promise(r=>server.close(r));await pool.end();});
test('calendar boundaries use local midnight and Monday',()=>{const b=boundaries(new Date('2026-09-06T22:00:00Z'),330);assert.equal(b.day,'2026-09-07');assert.equal(new Date(b.week).toISOString(),'2026-09-07T00:00:00.000Z');});
test('basic routes return real MySQL data',async()=>{assert.equal(await (await fetch(base+'/')).text(),'Gaming Habit & Behavior Analyzer API is running!');assert.equal((await request('/health')).data.database,'mysql');assert.ok((await request('/players')).data.some(p=>p.player_id===player));assert.equal((await request('/games')).data.length,4);assert.equal((await fetch(base+'/dashboard/')).status,200);});
test('empty player has zero analytics and invalid players return 404',async()=>{const r=await request('/dashboard/'+player);assert.equal(r.status,200);assert.equal(r.data.summary.today,0);assert.equal(r.data.summary.most_played,null);assert.equal(r.data.daily.length,30);assert.equal((await request('/dashboard/99999999')).status,404);assert.equal((await request('/dashboard/abc')).status,400);});
test('session lifecycle, concurrent starts, and library validation',async()=>{assert.equal((await request('/sessions/start','POST',{player_id:player,game_id:2})).status,400);const results=await Promise.all([request('/sessions/start','POST',{player_id:player,game_id:1}),request('/sessions/start','POST',{player_id:player,game_id:1})]);assert.deepEqual(results.map(r=>r.status).sort(),[201,409]);const live=(await request('/sessions/'+player)).data;assert.equal(live.length,1);assert.equal(live[0].duration_minutes,null);assert.equal((await request('/sessions/end','POST',{player_id:player})).status,200);assert.equal((await request('/sessions/end','POST',{player_id:player})).status,409);assert.notEqual((await request('/sessions/'+player)).data[0].duration_minutes,null);});
test('cross-midnight sessions are split between calendar days',async()=>{await query('DELETE FROM PLAYER_SESSIONS WHERE player_id=?',[player]);await query('INSERT INTO PLAYER_SESSIONS(player_id,game_id,platform_id,session_start,session_end) VALUES(?,1,1,UTC_DATE()-INTERVAL 1 DAY-INTERVAL 30 MINUTE,UTC_DATE()-INTERVAL 1 DAY+INTERVAL 30 MINUTE)',[player]);const r=(await request('/dashboard/'+player)).data;assert.equal(r.daily.at(-2).minutes,30);assert.equal(r.daily.at(-3).minutes,30);assert.equal(r.summary.longest_session,60);assert.equal(r.summary.average_daily,2);});
test('purchases validate amount and update totals',async()=>{const payload={player_id:player,game_id:1,amount:149.95,purchase_type:'In-game',note:'Test purchase'};assert.equal((await request('/purchases','POST',{...payload,amount:-1})).status,400);assert.equal((await request('/purchases','POST',{...payload,amount:1.234})).status,400);assert.equal((await request('/purchases','POST',payload)).status,201);const s=(await request('/dashboard/'+player)).data.summary;assert.equal(s.total_spending,149.95);assert.equal(s.monthly_spending,149.95);});
test('limit updates retain exactly one current history row',async()=>{const value={daily_playtime_limit:120,weekly_playtime_limit:840,monthly_spending_limit:2000,change_reason:'Testing'};assert.equal((await request('/limits/'+player,'PUT',value)).status,200);assert.equal((await request('/limits/'+player,'PUT',{...value,daily_playtime_limit:90})).status,200);const d=(await request('/dashboard/'+player)).data;assert.equal(d.limits.daily_playtime_limit,90);assert.equal(d.history.length,2);assert.equal(d.history.filter(h=>!h.effective_to).length,1);assert.equal((await request('/limits/'+player,'PUT',{...value,weekly_playtime_limit:0})).status,400);});
test('achievement earning rejects duplicates and games outside the library',async()=>{assert.equal((await request('/achievements/earn','POST',{player_id:player,achievement_id:4})).status,400);assert.equal((await request('/achievements/earn','POST',{player_id:player,achievement_id:1})).status,201);assert.equal((await request('/achievements/earn','POST',{player_id:player,achievement_id:1})).status,409);assert.equal((await request('/dashboard/'+player)).data.summary.achievement_points,10);});
test('planned analysis APIs and views execute',async()=>{for(const metric of ['today','week','month','spending','most-played','longest-session'])assert.equal((await request('/analysis/'+metric+'/'+player)).status,200);for(const view of ['VW_PLAYER_PLAYTIME_SUMMARY','VW_GAME_POPULARITY','VW_SPENDING_ANALYSIS','VW_ACHIEVEMENT_PROGRESS','VW_LIMIT_COMPLIANCE','VW_BEHAVIOR_TRENDS'])assert.ok(Array.isArray(await query('SELECT * FROM '+view)));});
